### ISSUE TITLE
interpretation of the significance results

### ISSUE THREAD

**Issue by whiteorchid** [igrabski/sc-SHC#13]
Dear author, 

Thanks a lot for your great innovative tool of sc-SHC!

May I apply for your guidance on the interpretation of the significance results? 

Does it mean the **_best cluster is 11_** based on the picture of below? 

The cluster used for input of `new_clusters <- testClusters(data, as.character(clusters))  ` is the clustered labels from Seurat, which has 12 clusters. 

What is the **number 0.55** after cluster 8 means?

Thank you very much for your kind guidance! 

Best,

<img width="269" alt="image" src="https://github.com/igrabski/sc-SHC/assets/6839620/9bec420b-ad16-4388-908c-076935e192ae">

**Comment by igrabski** [comment]
Thanks for trying out our tool!

The `testClusters` function takes a set of pre-computed clusters as input and then decides whether any of them should be merged. In this case, it looks like the 12 original clusters were merged into 11 final clusters. To see exactly how, you can compare `new_clusters[[1]]`, which contains the new cluster labels, to your previous cluster labels `as.character(clusters)`. 

The output you are showing here is a visualization of the tree of clusters that was tested as part of our approach. The numbers next to each node or cluster represent the adjusted p-value from assessing whether the clusters below represent distinct distributions or not. As you can see, many of the adjusted p-values here are 0, suggesting high confidence in the following clusters. However, here, Cluster 8 combines two of the original clusters, but the adjusted p-value for differentiating those two clusters is 0.55, which is why we keep those two clusters together.
