### ISSUE TITLE
Cannot extract p-values from cluster comparisons

### ISSUE THREAD

**Issue by sg3451** [igrabski/sc-SHC#22]
Is there a way to extract the p-values from the 'testClusters' function? The output is currently a list with 2 elements but none of them contain statistical significance results. One element of the list appears to be a dendogram but it is hard to interpret it.

**Comment by igrabski** [comment]
Hi, the p-values are printed after the colon next to the node/cluster labels in the dendrogram-type output (the second element of the list). They can be interpreted as the p-value corresponding to splitting that node/cluster. If no p-value is printed next to any particular cluster, it's because no further split was evaluated within that cluster (e.g. no further split may be possible if that cluster already represents one of the original inputted clusters).

**Comment by sg3451** [comment]
Thanks very much for the prompt response! Just so I understand it
correctly, in the following output, the splits at Node 0, Node 1, Node 2
and Node 3 are significant. Ultimately, scSHC is reporting 5 clusters based
on the node splits (named Cluster 1-5) - is this correct? There are no
further splits from any of these 5 clusters?

Node 0: 0
2  ¦--Node 1: 0
3  ¦   ¦--Cluster 1
4  ¦   °--Node 3: 0
5  ¦       ¦--Cluster 4
6  ¦       °--Cluster 5
7  °--Node 2: 0
8      ¦--Cluster 2
9      °--Cluster 3

**Comment by igrabski** [comment]
Yes that is correct!

**Comment by sg3451** [comment]
Excellent - thank you again for the quick response. I appreciate it.

Regards,

Sujoy
