### ISSUE TITLE
how to test my NMF cluster

### ISSUE THREAD

**Issue by Phoenix12580** [igrabski/sc-SHC#29]
Hi, i saw this nice package in Wechat  and use it 

I want to used it to identify Epi cell  clusters, however, Epi from tumor sample have huge heterogeneity.

I performed NMF to find the meta program, and used these NMF meta progrem ucell score as the PCA find clusters.

How should I change the input for scSHC?

Thank you for your work and reply!

**Comment by igrabski** [comment]
Hi, thanks for the kind words! If you have a set of existing clusters that you want to test, you can use the `testClusters` function to input a vector of cluster labels.

**Comment by Phoenix12580** [comment]
> Hi, thanks for the kind words! If you have a set of existing clusters that you want to test, you can use the `testClusters` function to input a vector of cluster labels.您好，感谢您的赞美！如果您有一组现有的聚类集需要测试，可以使用 `testClusters` 函数输入聚类标签向量。

Yeah, if i want to use scSHC to find cluster, and use NMF score as the PCA result,  how should i do?

**Comment by igrabski** [comment]
Ah, I misunderstood your question -- there isn't a way to change the internal dimension reduction, and I wouldn't recommend it since it is all part of the method. The only alternative I can think of is to actually apply the original general-purpose [SHC package](https://github.com/pkimes/sigclust2/tree/master) (not tailored to single-cell data) using the PCA scores / any other transformed version as the input data, as long as you think the Gaussian assumption is reasonable.

**Comment by Phoenix12580** [comment]
> Ah, I misunderstood your question -- there isn't a way to change the internal dimension reduction, and I wouldn't recommend it since it is all part of the method. The only alternative I can think of is to actually apply the original general-purpose [SHC package](https://github.com/pkimes/sigclust2/tree/master) (not tailored to single-cell data) using the PCA scores / any other transformed version as the input data, as long as you think the Gaussian assumption is reasonable.啊，我误解了你的问题——无法更改内部降维方式，而且我不建议这样做，因为这都是方法的一部分。我能想到的唯一替代方案是实际应用原始通用 SHC 包（未针对单细胞数据定制），使用 PCA 得分/任何其他转换版本作为输入数据，只要你认为高斯假设是合理的。

Thank a lot! Get it.   I will used the scSCH pieline and test my cluster
